name: Dispersed Network Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn prepare
      - run: yarn build

      - name: Dispersed Release
        uses: dispersed-labs/dispersed-release-action@v1
        with:
          build_dir: build
          bundle_name: uniswap-${{ github.ref_name }}.tgz
          github_token: ${{ secrets.GITHUB_TOKEN }}
